!
!  INCLUDE FILENAME:  R_elec_ed_lup_subs.inc
!
!  Include file containing the constant parameters for creating
!  the Electron Energy Deposition files.
!

      INTEGER    ENERGY_LEVELS     ! Number of energy levels in lookup
      PARAMETER (ENERGY_LEVELS = 63)

      INTEGER    ALTITUDES         ! Number of altitude levels in lookup
      PARAMETER (ALTITUDES = 88)

      INTEGER    SPECTRA_LEVELS    ! Number of spectra levels in
      PARAMETER (SPECTRA_LEVELS = 50)  ! user defined spectra
