clean:
	-@(cd src;                make clean)
	-@(cd srcEmpty;           make clean)
	-@(cd doc;                make clean)

distclean:
	-@(cd src;                make distclean)
	-@(cd srcEmpty;           make distclean)
	-@(cd doc;                make distclean)
