clean:
	-@(cd srcIndices;       make clean)
	-@(cd srcMagnetogram;   make clean)
	-@(cd srcDemt;          make clean)

distclean:
	-@(cd srcIndices;       make distclean)
	-@(cd srcMagnetogram;   make distclean)
	-@(cd srcDemt;          make distclean)
